### PR TITLE
Missing systems alert msg

### LINKED ISSUE #1597: Create Request checks System Requires warning
When a Request is being created, if a required system is not in an operational status, throw a warning message to the requester.

Either: "Unable to determine the status of required system N, proceed with caution" or "Required system N is in status X, proceed with caution"

Or something to the effect you can make the request, but it could fail due to this dependency.

### PR DESCRIPTION
**Pull request by 1maple1**
Fixes: #1597

### CODE REVIEW

File: src/ui/src/js/controllers/command_view.js [hunk 1]
```diff
@@ -98,6 +102,27 @@ export default function commandViewController(
...
+      const requires = $scope.system.requires;
+      const missingSystems = [];
+      requires.forEach((req) => {
+        const system = SystemService.findSystem($scope.system.namespace, req, 'latest');
+        const notRunning = system.instances.every((instance) => instance.status != 'RUNNING');
+        if (notRunning) {
+          missingSystems.push(system.name);
+        }
+      });
+      helptext = 'Unable to determine the status of required system(s): ' +
```
Comment (TheBurchLog) [inline src/ui/src/js/controllers/command_view.js]: Slightly different wording? They might have been found, but just were not running. So we did determine the status of the required system.

**Review by TheBurchLog — APPROVED** [review]
